### ISSUE TITLE
Push failing on Nextcloud Hub V18...

### ISSUE THREAD

**Issue by noci2012** [nextcloud/push#76]
System fails completely after installing / enabling Push.
Interface 'OCP\Push\Helper\IPushHelper' not found at ...../apps/push/lib/Helper/PushHelper.php#78

**Comment by kesselb** [comment]
Make sense :+1: 

I don't know why the app is released as 18 compatible. Some changes are necessary to nextcloud/server to make this app work (https://github.com/nextcloud/server/tree/stratos) but they are not merged hence not part of 18.

@daita would you mind to remove (or tag as 19) the app from the store again?

**Comment by kesselb** [comment]
> I don't know why the app is released as 18 compatible.

As per https://github.com/nextcloud/push/releases the app was released in September 2019. At this time 18 was the development version. I guess they just forgot to update the `min-version`.

**Comment by ifconfigex** [comment]
I have this problem too. Also OCC is not functioning at all.
I tried using OCC to disable the push app. Running ANY occ command will receive the following:
`
PHP Fatal error:  Interface 'OCP\Push\Helper\IPushHelper' not found in /var/www/html/custom_apps/push/lib/Helper/PushHelper.php on line 78
`
So is there a way to disable push app without OCC? Help!

**Comment by ifconfigex** [comment]
Solved by just deleting the push app folder.
`/var/www/html/custom_apps/push`
Delete this folder then the app is disabled.

**Comment by kesselb** [comment]
cc @nextcloud/appstore could someone unpublish the app from the app store please?

**Comment by jospoortvliet** [comment]
I've asked sysadmin to do this!

**Comment by blizzz** [comment]
done

**Comment by kesselb** [comment]
Thank you @blizzz :+1:
